//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.PatientInformation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PIDataContracts", Namespace="http://schemas.datacontract.org/2004/07/Service.DataContracts.PatientInformation")]
    [System.SerializableAttribute()]
    public partial class PIDataContracts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectIdField, value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientInformation.PatientInformation")]
    public interface PatientInformation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientInformation/GetPatientInformation", ReplyAction="http://tempuri.org/PatientInformation/GetPatientInformationResponse")]
        ConsoleClient.PatientInformation.PIDataContracts GetPatientInformation(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientInformation/GetPatientInformation", ReplyAction="http://tempuri.org/PatientInformation/GetPatientInformationResponse")]
        System.Threading.Tasks.Task<ConsoleClient.PatientInformation.PIDataContracts> GetPatientInformationAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientInformation/GetAllPatientInformation", ReplyAction="http://tempuri.org/PatientInformation/GetAllPatientInformationResponse")]
        ConsoleClient.PatientInformation.PIDataContracts[] GetAllPatientInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientInformation/GetAllPatientInformation", ReplyAction="http://tempuri.org/PatientInformation/GetAllPatientInformationResponse")]
        System.Threading.Tasks.Task<ConsoleClient.PatientInformation.PIDataContracts[]> GetAllPatientInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientInformationChannel : ConsoleClient.PatientInformation.PatientInformation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientInformationClient : System.ServiceModel.ClientBase<ConsoleClient.PatientInformation.PatientInformation>, ConsoleClient.PatientInformation.PatientInformation {
        
        public PatientInformationClient() {
        }
        
        public PatientInformationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientInformationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientInformationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientInformationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleClient.PatientInformation.PIDataContracts GetPatientInformation(string id) {
            return base.Channel.GetPatientInformation(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.PatientInformation.PIDataContracts> GetPatientInformationAsync(string id) {
            return base.Channel.GetPatientInformationAsync(id);
        }
        
        public ConsoleClient.PatientInformation.PIDataContracts[] GetAllPatientInformation() {
            return base.Channel.GetAllPatientInformation();
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.PatientInformation.PIDataContracts[]> GetAllPatientInformationAsync() {
            return base.Channel.GetAllPatientInformationAsync();
        }
    }
}
